apiVersion: v1
kind: ConfigMap
metadata:
  name: feature-toggle-config
data:
  FEATURE_DARK_MODE: 'true'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ecom-web
  name: ecom-web
spec:
  selector:
    matchLabels:
      app: ecom-web
  template:
    metadata:
      labels:
        app: ecom-web
    spec:
      containers:
      - image: 192.168.1.100:5000/ecom-web
        imagePullPolicy: Always
        name: ecom-web
        ports:
        - containerPort: 80
          protocol: TCP
        env:
          - name: FEATURE_DARK_MODE
            valueFrom:
              configMapKeyRef:
                name: feature-toggle-config
                key: FEATURE_DARK_MODE
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: mariadb
                key: host
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: mariadb
                key: user
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mariadb
                key: password
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: mariadb
                key: name
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
