datadog:
  apiKeyExistingSecret: datadog-secret
  site: datadoghq.com
  # Requires supported node image version
  kubelet:
    host:
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    hostCAPath: /etc/kubernetes/certs/kubeletserver.crt
  logs:
    enabled: true
    containerCollectAll: true
providers:
  aks:
    enabled: true