name: Deploy Ecom Web to Homelab
on:
  push:
    branches:
      - main

env:
  KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
jobs:
  build:
    #runs-on: self-hosted
    runs-on: arc-runner-setx
    steps:
      - name: Checkout Code x
        uses: actions/checkout@v2
  
      - name: Build Container
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: 192.168.1.100:5000/ecom-web:latest
          file: Dockerfile

  deploy:
    needs: [build]

    runs-on: arc-runner-setx
    steps:
      - name: Checkout Code x
        uses: actions/checkout@v2

      - name: Deploy MariaDB (deployment)
        uses: actions-hub/kubectl@master
        with:
          args: apply -f k3s/mariadb-deployment.yaml

      - name: Deploy MariaDB (service)
        uses: actions-hub/kubectl@master
        with:
          args: apply -f k3s/mariadb-service.yaml
                
      - name: Deploy Application (deployment)
        uses: actions-hub/kubectl@master
        with:
          args: apply -f k3s/app-deployment.yaml

      - name: Deploy Application (service)
        uses: actions-hub/kubectl@master
        with:
          args: apply -f k3s/app-service.yaml

      - name: Rollout Application (deployment)
        uses: actions-hub/kubectl@master
        with:
          args: rollout restart deployment/ecom-web